<p style="text-align:justify">Agrawals are basically a commercial community or Vaishyas. They are one of the most respectable and enterprising of mercantile tribes. Two of Emperor Akbar’s famous ministers are said to have been Agrawals, viz, Todarmal, who introduced an assessment of land, and Madhushah, who introduced ‘Madhushahi’ pice.<br/><br/></p>
<div class="col-sm-8 table-responsive">
						<table class="table table-title">
							<thead>
								<tr style="background-color:#034285;color:#fff">
									<th>No.</th>
									<th>GOTRA</th>
									<th>LORD OF GOTRA</th>
									<th>SAGE</th>
                                    <th>VED & BRANCH</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Garg</td>
									<td>Pushpadev</td>
									<td>Garg</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Goyal</td>
									<td>Gendumal</td>
									<td>Gobhil</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Goyan</td>
									<td>Godhar</td>
									<td>Gautam</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>4</td>
									<td>Bansal</td>
									<td>Virbhan</td>
									<td>Vatsa</td>
                                    <td>Kauttham(Sam)</td>
								</tr>
                                <tr>
									<td>5</td>
									<td>Kansal</td>
									<td>Manipal</td>
									<td>Kaushik</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>6</td>
									<td>Singhal</td>
									<td>Sindhupati</td>
									<td>Shandilya</td>
                                    <td>Kauttham(Sam)</td>
								</tr>
                                <tr>
									<td>7</td>
									<td>Mangal</td>
									<td>Amritsen</td>
									<td> Mandavya</td>
                                    <td>Sakalya(Yaj)</td>
								</tr>
                                <tr>
									<td>8</td>
									<td>Jindal</td>
									<td>Jaitrasangh</td>
									<td>Jaimini</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>9</td>
									<td>Tingal</td>
									<td>Tambolkarna</td>
									<td>Tandya</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>10</td>
									<td>Aeron</td>
									<td>Indramal</td>
									<td>Aaurva</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>11</td>
									<td>Dharan</td>
									<td>Dhavandev</td>
									<td>Ghaumya</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>12</td>
									<td>Madhukul</td>
									<td>Madhavsen</td>
									<td>Mudgal</td>
                                    <td>Sakalya(Yaj)</td>
								</tr>
                                <tr>
									<td>13</td>
									<td>Bindal</td>
									<td>Vrinddev</td>
									<td>Vashista</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>14</td>
									<td>Mittal</td>
									<td>Mantrapati</td>
									<td>Maitreya</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>15</td>
									<td>Tayal</td>
									<td>Tarachand</td>
									<td>Taitireya</td>
                                    <td>Aausthambh(Kri)</td>
								</tr>
                                <tr>
									<td>16</td>
									<td>Bhandal</td>
									<td>Vasudev</td>
									<td>Bhardwaj</td>
                                    <td>Madhuri(Yaj.)</td>
								</tr>
                                <tr>
									<td>17</td>
									<td>Kuchchal</td>
									<td>Karanchand</td>
									<td>Kashyap</td>
                                    <td>Kauttham(Sam)</td>
								</tr>
                                <tr>
									<td>18</td>
									<td>Nangal</td>
									<td>Narsev</td>
									<td>Nagendra</td>
                                    <td>Kauttham(Sam)</td>
								</tr>
							</tbody>
						</table>
					</div><!-- .col-sm-4 -->